[package]
name = "rslex"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]
build = "src/build.rs"

[[bin]]
name = "rslex"
path = "bin/rslex.rs"

[dependencies]
clap = "2.31.2"
libc = "0.2.0"
